# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(default='http://i.imgur.com/imPtltl.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='party',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservations.Reservation'),
        ),
        migrations.AlterField(
            model_name='table',
            name='joinable',
            field=models.BooleanField(default=False),
        ),
    ]
